### PR TITLE
Sort by ARN when interactively prompting so that accounts are grouped together when multiple roles exist

### PR DESCRIPTION
**Pull request by spasam**

### CODE REVIEW

**Comment by spasam** [comment]
@ruimarinho could you please take a look at this simple change? Thanks

**Comment by ruimarinho** [comment]
@spasam I like the idea but I would prefer if this was done under `credentials-manager.js` to make it testable (https://github.com/ruimarinho/gsts/blob/master/credentials-manager.js#L89). Can you make that change please?

**Comment by ruimarinho** [comment]
Thank you! Could you please add a test to ensure the feature remains covered? Appreciated!

**Comment by spasam** [comment]
Yeah, was just looking at that. Looks like I can re-order stuff in existing test and probably also add new one

**Comment by spasam** [comment]
Updated:
```sh
$ npm test

> gsts@4.0.1 test
> jest

 PASS  ./credentials-manager.test.js
 PASS  ./parser.test.js

Test Suites: 2 passed, 2 total
Tests:       25 passed, 25 total
Snapshots:   0 total
Time:        0.418 s, estimated 1 s
Ran all test suites.
```

**Pull request merged**
